# Generated by Django 5.2.6 on 2025-09-22 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=250)),
                ('image', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(default='', max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
